### ISSUE TITLE
Implement Travis CI Build

### ISSUE THREAD

**Issue by jwood803** [exercism/xfsharp#13]
After looking at a few other projects here on GitHub I've noticed that they were able to find a way to use Travis CI with .NET projects. After a bit of searching it seems there is a way to [implement](http://danlimerick.wordpress.com/2013/02/03/build-your-open-source-net-project-on-travis-ci/) [this](http://stackoverflow.com/questions/16751772/how-do-i-use-travis-ci-with-c-sharp-or-f).

I can definitely take a look at implementing this with F# and C#, but I'll admit I've never messed with these kinds of builds before.

**Comment by ErikSchierboom** [comment]
As far as I can tell, the Travis build works nicely. So perhaps this issue can be closed?

**Comment by jwood803** [comment]
I was hoping to add FAKE to it so it can actually build and run the tests. Unfortunately, I haven't gotten too far with it :disappointed:

**Comment by ErikSchierboom** [comment]
@jwood803 Have you consider using AppVeyor?

**Comment by jwood803** [comment]
I've [started](https://ci.appveyor.com/project/jwood803/xfsharp) to :}

Maybe I should pick this back up. Would be great to learn more on FAKE.

**Comment by ErikSchierboom** [comment]
Cool, appveyor is a really nice tool. FAKE is something I wanted to get to learn to for a long time. Might look into it soon.

**Comment by ErikSchierboom** [comment]
@jwood803 I've been looking into FAKE lately, and I think I can be of assistance here. The only thing is that FAKE expects a project or solution file as far as I can tell, and we don't have one. Should we create one?

**Comment by jwood803** [comment]
Awesome! I *might* still have a branch there with my changes so far.

I was attempting to compile the files directly since FAKE exposes the F# compiler. You have any thoughts on that approach?

**Comment by ErikSchierboom** [comment]
I haven't looked into that yet. Do you have any sample code?

**Comment by jwood803** [comment]
Not complete at all but here's what I've started on - https://github.com/jwood803/xfsharp/blob/build/build.fsx

**Comment by ErikSchierboom** [comment]
Thanks, I'll see if I can get something working.

**Comment by jwood803** [comment]
Awesome! I'll be glad to help, as well, if anything comes up.

**Comment by ErikSchierboom** [comment]
I managed to get something working! You can find the code in my [fake-testing](https://github.com/ErikSchierboom/xfsharp/tree/fake-testing) branch. 

Here is how it works:

- You execute the build using `build.ps1` (once that is done, I'll work on a shell version).
- The `build.sh1` file uses FAKE to execute `build.fsx`

The build script does the following things, in order:

- Clean the build directory (defaults to `"./build"`).
- Copies the `exercises` directory to the build directory.
- The copied `.fs` files in the build directory are modified to strip any `Ignore` attributes. Otherwise most tests would not run.
- Use the F# compiler service to create a DLL from the modified `.fs` files in the build directory.
- Use the NUnit 3 console runner to run the tests (the NUnit 2 console runner failed).

And that's it! All tests are then run (they all pass by the way):

![image](https://cloud.githubusercontent.com/assets/135246/12638914/e7113818-c5a0-11e5-8f7d-6ac9c38509f4.png)

Now what is left is to decide are some details. For example, do we want the `.ps1` script to download any (NuGet) dependencies (like NUnit, the NUnit console runner and FAKE)? At the moment, I've included the dependencies in the repository, but that could be left out of course. And do we also want to download NuGet itself from the build script?

**Comment by jwood803** [comment]
@ErikSchierboom That's awesome! Looks like you did much better than I did. :]

Usually dependencies are left out and the `.sh` or `.ps` script will redownload if they aren't found using NuGet or Paket.

**Comment by ErikSchierboom** [comment]
@jwood803 Okay, I'll modify the script to download ll dependencies then.

**Comment by ErikSchierboom** [comment]
@jwood803 I've updated the script to download the dependencies, added a UNIX bash script and submitted it as a [PR](#55). Could you check if things work as you expect?

**Comment by jwood803** [comment]
Awesome! I'll check it out over the next day or two. I also don't see why we can't do the same in the C# repository. I *believe* FAKE can use the C# compiler, as well.

**Comment by ErikSchierboom** [comment]
Well, I already searched for that but I could not find anything about Roslyn. Maybe that would require us to write a FAKE plugin?

**Comment by jwood803** [comment]
The [CscHelper](http://fsharp.github.io/FAKE/apidocs/fake-cschelper.html) wouldn't work? Granted, I'm just speculating and haven't used it.

**Comment by ErikSchierboom** [comment]
Whoops! I totally missed that. I was searching for Roslyn and came up empty. This looks promising! I'll be looking at that later.

**Comment by ErikSchierboom** [comment]
This is fixed by PR #55.

**Comment by jwood803** [comment]
Heh, @ErikSchierboom I just saw this was just pushed :p

https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FscHelper.fs

**Comment by ErikSchierboom** [comment]
@jwood803 Yes, the `FscHelper` module is what I use in my FAKE script. I'm very happy everything works :)

**Comment by jwood803** [comment]
Nice! It must have just been updated. I think I saw the last commit to it was around 24 hours ago from now.

**Comment by ErikSchierboom** [comment]
@jwood803 Indeed. Next up is checking to see if I can get something to work for the C# track.
