### ISSUE TITLE
Should we use libraries in our examples?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#96]
For some exercises, it makes sense to use an external library to do the heavy lifting. A prime example of this is when you need to do some more advanced text parsing, for example in the [wordy](exercises/wordy/Example.fs) exercise. For that specific exercise, it might make sense to use the [FParsec](http://www.quanttec.com/fparsec/) library. 

Should we allow ourselves to use libraries in our example exercises (only when it makes sense of course)? The Haskell track does take this approach. They even put some comments in the exercise's test file that indicate that the user might consider using a specific library to implement it. We could thus point the user to FParsec. We should of course not force users to use these libraries.

What do you think?

**Comment by kytrinyx** [comment]
I think that part of learning a language is to become familiar with the tools that let you use that language to solve specific types of problems.

In the Go track we've avoided libraries, but only because the Go standard library is big and covers everything we've had a need for.

I think that it would make sense to use (and recommend using) things like FParsec.

**Comment by ErikSchierboom** [comment]
Thanks for the reaction. I'll use libraries only when it makes sense of course.
